# Generated by Django 2.1.3 on 2019-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_firma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='nazwafirmy',
        ),
        migrations.AlterField(
            model_name='user',
            name='nrindeks',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pesel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
