# Generated by Django 2.1.3 on 2019-01-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190112_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nrindeks',
            field=models.IntegerField(blank=True, max_length=6, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pesel',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
