# Generated by Django 2.1.3 on 2019-01-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20190113_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opiekun',
            field=models.BooleanField(default=False),
        ),
    ]
