# Generated by Django 2.1.3 on 2019-01-09 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_firma'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grupa',
            fields=[
                ('id_Grupy', models.AutoField(primary_key=True, serialize=False)),
                ('imieUczestnika', models.CharField(max_length=45)),
                ('nazwiskoUczestnika', models.CharField(max_length=45)),
                ('imieProwadzacego', models.CharField(max_length=45)),
                ('nazwiskoProwadzacego', models.CharField(max_length=45)),
                ('id_Firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Firma')),
            ],
        ),
        migrations.CreateModel(
            name='Praktyki',
            fields=[
                ('id_Praktyki', models.AutoField(primary_key=True, serialize=False)),
                ('iloscMiejscMax', models.IntegerField(blank=True, null=True)),
                ('iloscMiejscZajetych', models.IntegerField(blank=True, null=True)),
                ('dataUtworzenia', models.DateField(auto_now_add=True)),
                ('dataRozpoczecia', models.DateField(blank=True, null=True)),
                ('dataZakonczenia', models.DateField(blank=True, null=True)),
                ('czyPlatne', models.BooleanField(blank=True, null=True)),
                ('wynagrodzenie', models.CharField(blank=True, max_length=45, null=True)),
                ('stanowisko', models.CharField(max_length=45)),
                ('opis', models.TextField(blank=True, max_length=255, null=True)),
                ('miasto', models.CharField(max_length=45)),
                ('id_Firma', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Firma')),
            ],
        ),
        migrations.AddField(
            model_name='grupa',
            name='id_Praktyki',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SRP.Praktyki'),
        ),
    ]
