# Generated by Django 2.1.3 on 2019-01-12 15:40

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupa',
            name='id_Firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='praktyki',
            name='czyPlatne',
            field=models.BooleanField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0, message='Wartość większa od zera')]),
        ),
        migrations.AlterField(
            model_name='praktyki',
            name='id_Firma',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
