# Generated by Django 2.1.3 on 2019-01-12 19:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0003_auto_20190112_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praktyki',
            name='czyPlatne',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='praktyki',
            name='wynagrodzenie',
            field=models.CharField(blank=True, max_length=45, null=True, validators=[django.core.validators.MinValueValidator(0, message='Wartość większa od zera')]),
        ),
    ]
