# Generated by Django 2.1.3 on 2019-01-12 19:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0004_auto_20190112_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praktyki',
            name='wynagrodzenie',
            field=models.CharField(blank=True, default=0, max_length=45, null=True, validators=[django.core.validators.MinValueValidator(0, message='Wartość większa od zera')]),
        ),
    ]
