# Generated by Django 2.1.3 on 2019-01-12 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0006_auto_20190112_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praktyki',
            name='dataRozpoczecia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='praktyki',
            name='dataUtworzenia',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='praktyki',
            name='dataZakonczenia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
