# Generated by Django 2.1.3 on 2019-01-12 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0007_auto_20190112_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praktyki',
            name='dataRozpoczecia',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
