# Generated by Django 2.1.3 on 2019-01-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0008_auto_20190112_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praktyki',
            name='dataRozpoczecia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='praktyki',
            name='dataUtworzenia',
            field=models.DateField(auto_now_add=True),
        ),
    ]
