# Generated by Django 2.1.3 on 2019-01-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0009_auto_20190113_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praktyki',
            name='iloscMiejscZajetych',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
