# Generated by Django 2.1.3 on 2019-01-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0010_auto_20190113_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='praktyki',
            name='iloscMiejscMax',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='praktyki',
            name='iloscMiejscZajetych',
            field=models.CharField(blank=True, default=0, max_length=15, null=True),
        ),
    ]
