# Generated by Django 2.1.3 on 2019-01-15 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0011_auto_20190113_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='praktyki',
            name='dataUtworzenia',
        ),
    ]
