# Generated by Django 2.1.3 on 2019-01-15 00:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0012_remove_praktyki_datautworzenia'),
    ]

    operations = [
        migrations.AddField(
            model_name='praktyki',
            name='dataUtworzenia',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
