# Generated by Django 2.1.3 on 2019-01-16 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SRP', '0013_praktyki_datautworzenia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupa',
            name='id_Firma',
        ),
        migrations.RemoveField(
            model_name='grupa',
            name='imieProwadzacego',
        ),
        migrations.RemoveField(
            model_name='grupa',
            name='imieUczestnika',
        ),
        migrations.RemoveField(
            model_name='grupa',
            name='nazwiskoProwadzacego',
        ),
        migrations.RemoveField(
            model_name='grupa',
            name='nazwiskoUczestnika',
        ),
        migrations.AddField(
            model_name='grupa',
            name='uczestnik',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
