# Generated by Django 2.1.3 on 2019-01-16 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0014_auto_20190116_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupa',
            name='uczestnik',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
