# Generated by Django 2.1.3 on 2019-01-16 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SRP', '0015_auto_20190116_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupa',
            name='uczestnik',
        ),
        migrations.AddField(
            model_name='grupa',
            name='uczestnik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
