# Generated by Django 2.1.3 on 2019-01-16 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SRP', '0016_auto_20190116_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupa',
            name='uczestnik',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='User.nrindeks+', to=settings.AUTH_USER_MODEL),
        ),
    ]
